format_version: 10
pipelines:
  backend-deployment:
    group: deployment-group
    label_template: ${COUNT}
    lock_behavior: none
    display_order: 1
    materials:
      git-backend:
        git: https://github.com/suryaveerubhotla/simple-ui.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - Deploy:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
          jobs:
            run-commands:
              timeout: 0
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - |
                        echo "Exporting environment variables..."
                        export BUILD_DIR=/home/ubuntu/builds
                        export BE_TARGET_DIR=/home/ubuntu/prime-square
                        export BE_ARCHIVE_DIR=/home/ubuntu/archive
                        export SERVICE=PrimeSquare.service
                        export DB_SCRIPTS_DIR=/home/ubuntu/prime-square/database-scripts
                        export DB_USER=psdbadmin
                        export DB_PASS=6%EOm@Te1sb19Th6
                        export SFTP_HOST=192.168.56.106
                        export SFTP_USER=surya
                        export SFTP_KEY=/var/go/.ssh/id_rsa
                        export SFTP_UPLOADS_DIR=uploads

                        echo "Checking if service ${SERVICE} exists..."
                        if [ -f /etc/systemd/system/${SERVICE} ]; then
                          echo "${SERVICE} exists. Checking service status..."
                          sudo systemctl status ${SERVICE} > /dev/null 2>&1
                          if [ $? -eq 0 ]; then
                            echo "${SERVICE} is running. Stopping the service..."
                            sudo systemctl stop ${SERVICE} || { echo "Failed to stop ${SERVICE}"; exit 1; }
                          else
                            echo "${SERVICE} is not running."
                          fi
                        else
                          echo "${SERVICE} does not exist. Proceeding..."
                        fi

                        echo "Checking and creating BUILD_DIR if needed..."
                        if [ ! -d "${BUILD_DIR}" ]; then
                          echo "BUILD_DIR does not exist. Creating ${BUILD_DIR}..."
                          sudo mkdir -p "${BUILD_DIR}" || { echo "Failed to create ${BUILD_DIR}"; exit 1; }
                        else
                          echo "BUILD_DIR exists. Using existing ${BUILD_DIR}..."
                        fi
                        sudo chmod -R 775 "${BUILD_DIR}" || { echo "Failed to set permissions for BUILD_DIR"; exit 1; }
                        sudo chown -R go:go "${BUILD_DIR}" || { echo "Failed to change ownership of BUILD_DIR"; exit 1; }

                        echo "Checking for existing ps_be_*.zip files in BUILD_DIR..."
                        if ls "${BUILD_DIR}/ps_be_*.zip" > /dev/null 2>&1; then
                          echo "Found existing ps_be_*.zip files:"
                          ls "${BUILD_DIR}/ps_be_*.zip"
                          echo "Removing existing ps_be_*.zip files..."
                          sudo rm -f "${BUILD_DIR}/ps_be_*.zip" || { echo "Failed to remove existing zip files"; exit 1; }
                        else
                          echo "No existing ps_be_*.zip files found. Proceeding..."
                        fi

                        echo "Accessing SFTP machine to fetch the latest backend zip file..."
                        sudo -u go sftp -o StrictHostKeyChecking=no -i /var/go/.ssh/id_rsa ${SFTP_USER}@${SFTP_HOST} <<EOF
                        cd ${SFTP_UPLOADS_DIR}
                        get \$(ls -t ps_be_*.zip | head -1) ${BUILD_DIR}/
                        bye
                        EOF
                        if [ $? -ne 0 ]; then
                          echo "Failed to fetch backend.zip from SFTP."
                          exit 1
                        fi

                        echo "Checking and creating BE_TARGET_DIR if needed..."
                        if [ ! -d "${BE_TARGET_DIR}" ]; then
                          echo "BE_TARGET_DIR does not exist. Creating ${BE_TARGET_DIR}..."
                          sudo mkdir -p "${BE_TARGET_DIR}" || { echo "Failed to create ${BE_TARGET_DIR}"; exit 1; }
                        else
                          echo "BE_TARGET_DIR exists. Using existing ${BE_TARGET_DIR}..."
                        fi

                        echo "Changing permissions of BE_TARGET_DIR to go:go..."
                        sudo chown -R go:go "${BE_TARGET_DIR}" || { echo "Failed to change permissions of BE_TARGET_DIR"; exit 1; }
                        sudo chmod -R 775 "${BE_TARGET_DIR}" || { echo "Failed to set permissions for BE_TARGET_DIR"; exit 1; }

                        echo "Unzipping the backend artifacts to BE_TARGET_DIR..."
                        sudo unzip -o "${BUILD_DIR}/ps_be_*.zip" -d "${BE_TARGET_DIR}" || { echo "Failed to unzip backend.zip"; exit 1; }

                        echo "Listing extracted files in BE_TARGET_DIR..."
                        sudo ls -l "${BE_TARGET_DIR}"

                        echo "Checking and copying service file if needed..."
                        if [ ! -f /etc/systemd/system/${SERVICE} ]; then
                          sudo cp "${BE_TARGET_DIR}/service/${SERVICE}" /etc/systemd/system/ || { echo "Failed to copy service file"; exit 1; }

                          echo "Enabling the service..."
                          sudo systemctl enable ${SERVICE} || { echo "Failed to enable ${SERVICE}"; exit 1; }
                        else
                          echo "Service file already exists. Skipping copy."
                        fi

                        echo "Making wrapper.sh executable..."
                        sudo chmod +x "${BE_TARGET_DIR}/wrapper.sh" || { echo "Failed to make wrapper.sh executable"; exit 1; }

                        echo "Reloading systemd daemon..."
                        sudo systemctl daemon-reload || { echo "Failed to reload systemd daemon"; exit 1; }

                        echo "Setting permissions and ownership for database scripts..."
                        sudo chmod 755 /home/ubuntu/prime-square/database-scripts
                        sudo chown go:go /home/ubuntu/prime-square/database-scripts
                        sudo chmod 644 "${DB_SCRIPTS_DIR}"/*.sql || { echo "Failed to set permissions for database scripts"; exit 1; }
                        sudo chown go:go "${DB_SCRIPTS_DIR}"/*.sql || { echo "Failed to change ownership of database scripts"; exit 1; }

                        echo "Executing database scripts..."
                        sudo mysql < "${DB_SCRIPTS_DIR}/ddl_drop_schema_script.sql" -u ${DB_USER} -p${DB_PASS} || { echo "Failed to execute ddl_drop_schema_script.sql"; exit 1; }
                        sudo mysql < "${DB_SCRIPTS_DIR}/idfc_primesquare_workflow_ddl_dml.sql" -u ${DB_USER} -p${DB_PASS} || { echo "Failed to execute primesquare_workflow_ddl_dml.sql"; exit 1; }
                        sudo mysql < "${DB_SCRIPTS_DIR}/ddl_create_scripts.sql" -u ${DB_USER} -p${DB_PASS} || { echo "Failed to execute ddl_create_scripts.sql"; exit 1; }
                        sudo mysql < "${DB_SCRIPTS_DIR}/dml_insert_scripts.sql" -u ${DB_USER} -p${DB_PASS} || { echo "Failed to execute dml_insert_scripts.sql"; exit 1; }
                        sudo mysql < "${DB_SCRIPTS_DIR}/ps_index_create.sql" -u ${DB_USER} -p${DB_PASS} || { echo "Failed to execute ps_index_create.sql"; exit 1; }

                        echo "Starting service..."
                        sudo systemctl start ${SERVICE} || { echo "Failed to start ${SERVICE}"; exit 1; }
                        sudo systemctl status ${SERVICE}

                        echo "Deployment complete."
              resources:
                - ubuntu
              environment_variables:
                GOCD_ENVIRONMENT: Frontandbackend

environments:
  Frontandbackend:
    pipelines:
      - backend-deployment