format_version: 10
pipelines:
  backend-deployment:
    group: deployment-group
    label_template: ${COUNT}
    lock_behavior: none
    display_order: 1
    materials:
      git-backend:
        git: https://github.com/suryaveerubhotla/backend-repo.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - Deploy-Backend:
          jobs:
            run-commands:
              tasks:
                - exec:
                    command: echo
                    arguments:
                      - "Deploying backend..."
environments:
  Frontandbackend:
    pipelines:
      - backend-deployment
