format_version: 10
pipelines:
  backend-deployment:
    group: deployment-group
    label_template: ${COUNT}
    lock_behavior: none
    display_order: 1
    materials:
      git-backend:
        git: https://github.com/suryaveerubhotla/simple-ui.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - Deploy-Backend:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
          jobs:
            run-commands:
              variables:
                BUILD_DIR: /home/ubuntu/builds
                BE_TARGET_DIR: /home/ubuntu/prime
                BE_ARCHIVE_DIR: /home/ubuntu/archive
                BE_TEMP_DIR: ${BE_ARCHIVE_DIR}/temp-extract
                SERVICE: PrimeSquare.service
              tasks:
                - script: |
                    #!/bin/bash
                    set -e

                    mkdir -p "${BE_ARCHIVE_DIR}"
                    mkdir -p "${BE_TEMP_DIR}"
                    mkdir -p "${BE_TARGET_DIR}"

                    BE_FILE=$(ls -t "${BUILD_DIR}"/*.be.*.tar.gz 2>/dev/null | head -n 1)

                    if [ -z "$BE_FILE" ]; then
                      echo "No BE build file found in ${BUILD_DIR}"
                      exit 1
                    fi

                    tar -xzf "$BE_FILE" -C "${BE_TEMP_DIR}"

                    rsync -a --delete "${BE_TEMP_DIR}/" "${BE_TARGET_DIR}/"

                    chmod -R 755 "${BE_TARGET_DIR}"

                    systemctl restart "${SERVICE}"

                    echo "Backend deployed successfully and service restarted"

environments:
  Frontandbackend: 
    pipelines:
      - backend-deployment
