format_version: 10
pipelines:
  backend-deployment:
    group: deployment-group
    label_template: ${COUNT}
    lock_behavior: none
    display_order: 1
    materials:
      git-backend:
        git: https://github.com/suryaveerubhotla/simple-ui.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - Deploy:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
          jobs:
            run-commands:
              timeout: 0
              variables:
                BUILD_DIR: /home/ubuntu/builds
                BE_TARGET_DIR: /home/ubuntu/prime-square
                BE_ARCHIVE_DIR: /home/ubuntu/archive
                SERVICE: PrimeSquare.service
                DB_SCRIPTS_DIR: /home/ubuntu/prime-square/database-scripts
                DB_USER: psdbadmin
                DB_PASS: 6%EOm@Te1sb19Th6
                SFTP_HOST: 172.16.7.116
                SFTP_USER: surya
                SFTP_UPLOADS_DIR: uploads
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - |
                        echo "Accessing SFTP machine to fetch the backend zip file..."
                        export BUILD_DIR=/home/ubuntu/builds
                        export SFTP_HOST=172.16.7.116
                        export SFTP_USER=surya
                        export SFTP_UPLOADS_DIR=uploads

                        echo "Creating build directory..."
                        mkdir -p "${BUILD_DIR}" || { echo "Failed to create ${BUILD_DIR}"; exit 1; }

                        echo "Downloading backend zip file from SFTP..."
                        sftp -o StrictHostKeyChecking=no -i "${SFTP_KEY}" ${SFTP_USER}@${SFTP_HOST} <<EOF
                        cd ${SFTP_UPLOADS_DIR}
                        get ps_be*.zip ${BUILD_DIR}/
                        bye
                        EOF
                        if [ $? -ne 0 ]; then
                          echo "Failed to fetch ps_be*.zip from SFTP."
                          exit 1
                        fi
                        
                        echo "Unzipping backend artifacts..."
                        unzip -o "${BUILD_DIR}/ps_be*.zip" -d "${BUILD_DIR}" || { echo "Failed to unzip ps_be*.zip"; exit 1; }

                        echo "Continuing with deployment steps..."
                        
                        
                        mkdir -p "${BE_TARGET_DIR}" || { echo "Failed to create ${BE_TARGET_DIR}"; exit 1; }
                        unzip -o "${BUILD_DIR}/" -d "${BE_TARGET_DIR}" || { echo "Failed to unzip ps_be"; exit 1; }

                        echo "Changing permissions to ubuntu:ubuntu..."
                        sudo chown -R ubuntu:ubuntu "${BE_TARGET_DIR}" || { echo "Failed to change ownership"; exit 1; }

                        echo "Copying service file..."
                        sudo cp "${BE_TARGET_DIR}/service/PrimeSquare.service" /etc/systemd/system/ || { echo "Failed to copy service file"; exit 1; }

                        echo "Making wrapper.sh executable..."
                        sudo chmod +x "${BE_TARGET_DIR}/wrapper.sh" || { echo "Failed to make wrapper.sh executable"; exit 1; }

                        echo "Reloading systemd daemon..."
                        sudo systemctl daemon-reload || { echo "Failed to reload systemd daemon"; exit 1; }

                        echo "Giving execute permissions to database scripts..."
                        sudo chmod -R +x "${DB_SCRIPTS_DIR}" || { echo "Failed to give execute permissions to database scripts"; exit 1; }

                        echo "Executing database scripts..."
                        mysql < "${DB_SCRIPTS_DIR}/ddl_drop_schema_script.sql" -u ${DB_USER} -p${DB_PASS} || { echo "Failed to execute ddl_drop_schema_script.sql"; exit 1; }
                        mysql < "${DB_SCRIPTS_DIR}/idfc_primesquare_workflow_ddl_dml.sql" -u ${DB_USER} -p${DB_PASS} || { echo "Failed to execute primesquare_workflow_ddl_dml.sql"; exit 1; }
                        mysql < "${DB_SCRIPTS_DIR}/ddl_create_scripts.sql" -u ${DB_USER} -p${DB_PASS} || { echo "Failed to execute ddl_create_scripts.sql"; exit 1; }
                        mysql < "${DB_SCRIPTS_DIR}/dml_insert_scripts.sql" -u ${DB_USER} -p${DB_PASS} || { echo "Failed to execute dml_insert_scripts.sql"; exit 1; }
                        mysql < "${DB_SCRIPTS_DIR}/ps_index_create.sql" -u ${DB_USER} -p${DB_PASS} || { echo "Failed to execute PS_Index.sql"; exit 1; }

                        echo "Enabling and starting service..."
                        sudo systemctl enable ${SERVICE} || { echo "Failed to enable ${SERVICE}"; exit 1; }
                        sudo systemctl start ${SERVICE} || { echo "Failed to start ${SERVICE}"; exit 1; }

                        echo "Checking service status..."
                        sudo systemctl status ${SERVICE}

                        echo "Deployment complete."
              resources:
                - ubuntu
              environment_variables:
                GOCD_ENVIRONMENT: Frontandbackend

environments:
  Frontandbackend:
    pipelines:
      - backend-deployment
