format_version: 10
pipelines:
  database-deployment:
    group: DB-group
    label_template: ${COUNT}
    materials:
      git-database:
        git: https://github.com/suryaveerubhotla/simple-ui.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - SetupDB:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            setup-database:
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - |
                        echo "Setting up environment variables..."
                        export DB_DIR=/home/ubuntu/database
                        export SFTP_HOST=172.16.7.116
                        export SFTP_USER=surya
                        export SFTP_KEY=/var/go/.ssh/id_rsa
                        export SFTP_UPLOADS_DIR=uploads
                        export BUILD_FILE="ps_be_1.1.26_idfc_1.1.13-9f56559-321.zip"
                        export DB_USER=psdbadmin
                        export SERVICE=PrimeSquare.service

                         echo "Checking if service ${SERVICE} exists..."
                        if [ -f /etc/systemd/system/${SERVICE} ]; then
                          echo "${SERVICE} exists. Checking service status..."
                          sudo systemctl status ${SERVICE} > /dev/null 2>&1
                          if [ $? -eq 0 ]; then
                            echo "${SERVICE} is running. Stopping the service..."
                            sudo systemctl stop ${SERVICE} || { echo "Failed to stop ${SERVICE}"; exit 1; }
                          else
                            echo "${SERVICE} is not running."
                          fi
                        else
                          echo "${SERVICE} does not exist. Proceeding..."
                        fi

                        echo "Creating and setting up DB_DIR..."
                        if [ ! -d "${DB_DIR}" ]; then
                          sudo mkdir -p "${DB_DIR}" || { echo "Failed to create ${DB_DIR}"; exit 1; }
                        fi
                        
                        sudo chown -R go:go "${DB_DIR}"

                        echo "Fetching the specified database build file from SFTP..."
                        sudo -u go sftp -o StrictHostKeyChecking=no -i ${SFTP_KEY} ${SFTP_USER}@${SFTP_HOST} <<EOF
                        cd ${SFTP_UPLOADS_DIR}
                        get ${BUILD_FILE} ${DB_DIR}/
                        bye
                        EOF
                        if [ $? -ne 0 ]; then
                          echo "Failed to fetch the specified database build file from SFTP."
                          exit 1
                        fi

                        echo "Extracting database scripts into DB_DIR..."
                        sudo unzip -o "${DB_DIR}/${BUILD_FILE}" -d "${DB_DIR}" || { echo "Failed to extract database scripts"; exit 1; }

                        echo "Setting execute permissions for database scripts..."
                        sudo chmod -R +x "${DB_DIR}" || { echo "Failed to set permissions"; exit 1; }

                         echo "Fetching DB password securely..."
                        DB_PASS=$(cat /var/go/secrets/db_pass)
                        if [ -z "${DB_PASS}" ]; then
                          echo "Database password is missing!"
                          exit 1
                        fi

                        echo "Dropping and recreating the database..."
                        mysql < "${DB_DIR}/database-scripts/ddl_drop_schema_script.sql" -u ${DB_USER} -p${DB_PASS} || { echo "Failed to execute ddl_drop_schema_script.sql"; exit 1; }
                        mysql < "${DB_DIR}/database-scripts/idfc_primesquare_workflow_ddl_dml.sql" -u ${DB_USER} -p${DB_PASS} || { echo "Failed to execute primesquare_workflow_ddl_dml.sql"; exit 1; }
                        mysql < "${DB_DIR}/database-scripts/ddl_create_scripts.sql" -u ${DB_USER} -p${DB_PASS} || { echo "Failed to execute ddl_create_scripts.sql"; exit 1; }
                        mysql < "${DB_DIR}/database-scripts/dml_insert_scripts.sql" -u ${DB_USER} -p${DB_PASS} || { echo "Failed to execute dml_insert_scripts.sql"; exit 1; }
                        mysql < "${DB_DIR}/database-scripts/ps_index_create.sql" -u ${DB_USER} -p${DB_PASS} || { echo "Failed to execute ps_index_create.sql"; exit 1; }
                        echo "Database setup complete."
                        
                        echo "Database setup completed, Removing contents."
                        sudo rm -rf ${DB_DIR} || { echo "Failed to remove contents in ${DB_DIR}"; exit 1; }

                        echo "Starting service..."
                        sudo systemctl start ${SERVICE} || { echo "Failed to start ${SERVICE}"; exit 1; }
                        sudo systemctl status ${SERVICE}

              resources:
                - ubuntu
              environment_variables:
                GOCD_ENVIRONMENT: database-pipeline

environments:
  database-pipeline:
    pipelines:
      - database-deployment
