format_version: 10
pipelines:
  frontend-deployment:
    group: deployment-group
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-505a42e:
        git: https://github.com/suryaveerubhotla/simple-ui.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - Stage1:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
            allow_only_on_success: false
          jobs:
            Job1:
              resources:
                - ubuntu
              timeout: 0
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - "-c"
                      - |
                        export BUILD_DIR=/home/ubuntu/builds
                        export BE_TARGET_DIR=/home/ubuntu/prime-square
                        export BE_ARCHIVE_DIR=/home/ubuntu/archive
                        export SERVICE=PrimeSquare.service
                        export DB_SCRIPTS_DIR=/home/ubuntu/prime-square/database-scripts
                        export DB_USER=psdbadmin
                        export DB_PASS=6%EOm@Te1sb19Th6
                        export SFTP_HOST=172.16.7.116
                        export SFTP_USER=surya
                        export SFTP_KEY=/var/go/.ssh/id_rsa
                        export SFTP_UPLOADS_DIR=uploads

                        echo "Ensure directories exist"
                        sudo mkdir -p $UI_ARCHIVE_DIR $BUILD_DIR
                        sudo chown ubuntu:ubuntu $UI_ARCHIVE_DIR $BUILD_DIR

                        echo "Fetch the latest file from SFTP by timestamp"
                        LATEST_FILE=$(sftp -o StrictHostKeyChecking=no -i $SFTP_KEY "$SFTP_USER@$SFTP_HOST" <<EOF | grep ps_ui_ | head -n 1
                        cd $SFTP_UPLOADS_DIR
                        ls -t ps_ui_*.zip
                        bye
                        EOF
                        )

                        if [ -z "$LATEST_FILE" ]; then
                          echo "No ps_ui_*.zip files found on SFTP server. Exiting."
                          exit 1
                        fi

                        echo "Latest file is: $LATEST_FILE"

                        echo "Download the latest file"
                        sftp -o StrictHostKeyChecking=no -i $SFTP_KEY "$SFTP_USER@$SFTP_HOST" <<EOF
                        cd $SFTP_UPLOADS_DIR
                        get "$LATEST_FILE" "$BUILD_DIR/$LATEST_FILE"
                        bye
                        EOF

                        echo "Verify the file exists"
                        if [ ! -f "$BUILD_DIR/$LATEST_FILE" ]; then
                          echo "Download failed or file not found: $BUILD_DIR/$LATEST_FILE"
                          exit 1
                        fi

                        echo "Downloaded $LATEST_FILE to $BUILD_DIR"

                        echo "Stop Apache"
                        sudo systemctl stop apache2

                        echo "Deploy the build"
                        if [ -d "$UI_TARGET_DIR" ]; then
                          sudo rm -rf $UI_TARGET_DIR
                        fi
                        sudo unzip "$BUILD_DIR/$LATEST_FILE" -d "$UI_TARGET_DIR"

                        echo "Update configuration"
                        sudo sed -i "s|https://ps-targethost:3804/prime-square|http://${TARGET_HOST}/prime-square|g" "$UI_TARGET_DIR/main.e1f206db06620922.js"
                        sudo sed -i "s|https://ps-targethost:3804/prime-square|http://${TARGET_HOST}/prime-square|g" "$UI_TARGET_DIR/assets/environment/environment.json"

                        echo "Restart Apache"
                        sudo systemctl start apache2.service
environments:
  Frontandbackend:
    pipelines:
      - frontend-deployment
