format_version: 10
pipelines:
  frontend-deployment:
    group: deployment-group
    label_template: ${COUNT}
    lock_behavior: none
    display_order: 2
    materials:
      git-frontend:
        git: https://github.com/suryaveerubhotla/simple-ui.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - Deploy-Frontend:
          jobs:
            run-commands:
              tasks:
                - exec:
                    command: echo
                    arguments:
                      - "Deploying frontend..."
environments:
  Frontandbackend:
    pipelines:
      - frontend-deployment