format_version: 10
pipelines:
  frontend:
    group: frontend-group
    label_template: ${COUNT}
    materials:
      git-frontend:
        git: https://github.com/suryaveerubhotla/simple-ui.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - Deploy:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            Deploy-Frontend:
              environment_variables:
                ENV_VARS_SCRIPT: env_vars.sh
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - |
                        source ${ENV_VARS_SCRIPT}
                        export BUILD_FILE="ps_be_1.1.26_idfc_1.1.13-8b07db6-319.zip"

                        echo "Creating UI_ARCHIVE directory if it doesn't exist..."
                        if [ ! -d "${UI_ARCHIVE}" ]; then
                          sudo mkdir -p "${UI_ARCHIVE}" || { echo "Failed to create UI_ARCHIVE directory"; exit 1; }
                        else
                          echo "UI_ARCHIVE directory already exists."
                        fi

                        sudo chown -R go:go "${UI_ARCHIVE}" || { echo "Failed to set ownership for UI_ARCHIVE"; exit 1; }

                        echo "Fetching UI build from SFTP server..."
                        sudo -u go sftp -o StrictHostKeyChecking=no -i ${SFTP_KEY} ${SFTP_USER}@${SFTP_HOST} <<EOF
                        cd ${SFTP_UPLOADS_DIR}
                        get ${BUILD_FILE} ${UI_ARCHIVE}/
                        bye
                        EOF
                        if [ $? -ne 0 ]; then
                          echo "Failed to fetch the UI build from SFTP."
                          exit 1
                        fi

                        echo "Listing contents of UI_ARCHIVE..."
                        ls -l "${UI_ARCHIVE}"

                        echo "Stopping Apache2 service..."
                        sudo systemctl stop apache2 || { echo "Failed to stop Apache2"; exit 1; }

                        echo "Removing existing UI_TARGET_DIR..."
                        sudo rm -rf "${UI_TARGET_DIR/prime-square}" || { echo "Failed to remove UI_TARGET_DIR"; exit 1; }

                        echo "Unzipping UI build to UI_TARGET_DIR..."
                        sudo unzip -o "${UI_ARCHIVE}/${BUILD_FILE}" -d "${UI_TARGET_DIR}" || { echo "Failed to unzip UI build"; exit 1; }


                        echo "permissions for UI_TARGET_DIR/prime-square"
                        sudo chown -R root:root "${UI_TARGET_DIR}/prime-square"


                        echo "Updating target host in configuration files..."
                        echo "Exporting TARGET_HOST: $TARGET_HOST"
                        sudo sed -i "s|https://ps-targethost:3804|http://$TARGET_HOST|g" "${UI_TARGET_DIR}/prime-square/main.e1f206db06620922.js" || { echo "Failed to update main.js"; exit 1; }

                        sudo sed -i "s|https://ps-targethost:3804|http://$TARGET_HOST|g" "${UI_TARGET_DIR}/prime-square/assets/environment/environment.json" || { echo "Failed to update environment.json"; exit 1; }

                        echo "Starting Apache2 service..."
                        sudo systemctl start apache2 || { echo "Failed to start Apache2"; exit 1; }

                        echo "Front-end deployment complete."
              resources:
                - ubuntu

environments:
  Frontandbackend:
    pipelines:
      - frontend
