format_version: 10
pipelines:
  frontend-deployment:
    group: deployment-group
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-505a42e:
        git: https://github.com/suryaveerubhotla/simple-ui.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - Stage1:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
            allow_only_on_success: false
          jobs:
            Job1:
              resources:
                - ubuntu
              environment_variables:
                BUILD_DIR: /home/ubuntu/builds
                UI_ARCHIVE_DIR: /home/ubuntu/ui-archive
                UI_TARGET_DIR: /var/www/html
                SERVICE: PrimeSquare.service
                DB_SCRIPTS_DIR: /home/ubuntu/prime-square/database-scripts
                DB_USER: psdbadmin
                DB_PASS: 6%EOm@Te1sb19Th6
                SFTP_HOST: 172.16.7.116
                SFTP_USER: surya
                SFTP_KEY: /var/go/.ssh/id_rsa
                SFTP_UPLOADS_DIR: uploads
                TARGET_HOST: 172.16.7.112
              timeout: 0
              tasks:
                - exec:
                    command: bash
                    arguments:
                      - "-c"
                      - |
                        echo "Ensure directories exist"
                        sudo mkdir -p $UI_ARCHIVE_DIR $BUILD_DIR
                        sudo chown ubuntu:ubuntu $UI_ARCHIVE_DIR $BUILD_DIR

                        echo "Fetch the latest file from SFTP by timestamp"
                        LATEST_FILE=$(sftp -o StrictHostKeyChecking=no -i $SFTP_KEY "$SFTP_USER@$SFTP_HOST" <<EOF
                        cd $SFTP_UPLOADS_DIR
                        ls -t ps_ui_*.zip | head -n 1
                        bye
                        EOF
                        )

                        if [ -z "$LATEST_FILE" ]; then
                          echo "No ps_ui_*.zip files found on SFTP server. Exiting."
                          exit 1
                        fi

                        echo "Latest file is: $LATEST_FILE"
                        sftp -o StrictHostKeyChecking=no -i $SFTP_KEY "$SFTP_USER@$SFTP_HOST" <<EOF
                        cd $SFTP_UPLOADS_DIR
                        get "$LATEST_FILE" "$BUILD_DIR/$LATEST_FILE"
                        bye
                        EOF

                        echo "Downloaded $LATEST_FILE to $BUILD_DIR"

                        echo "Extract and deploy the UI build"
                        sudo systemctl stop apache2
                        if [ -d "$UI_TARGET_DIR" ]; then
                          sudo rm -rf $UI_TARGET_DIR
                        fi
                        sudo unzip "$BUILD_DIR/$LATEST_FILE" -d "$UI_TARGET_DIR"

                        echo "Update configuration"
                        sudo sed -i "s|https://ps-targethost:3804/prime-square|http://${TARGET_HOST}/prime-square|g" "$UI_TARGET_DIR/main.e1f206db06620922.js"
                        sudo sed -i "s|https://ps-targethost:3804/prime-square|http://${TARGET_HOST}/prime-square|g" "$UI_TARGET_DIR/assets/environment/environment.json"

                        echo "Restart Apache"
                        sudo systemctl start apache2.service
environments:
  Frontandbackend:
    pipelines:
      - frontend-deployment
