format_version: 10
pipelines:
  frontend-deployment:
    group: deployment-group
    label_template: ${COUNT}
    lock_behavior: none
    display_order: 2
    materials:
      git-frontend:
        git: https://github.com/suryaveerubhotla/simple-ui.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - Deploy-Frontend:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
          jobs:
            run-commands:
              variables:
                BUILD_DIR: /home/ubuntu/builds
                UI_TARGET_DIR: /var/www/html
                UI_ARCHIVE_DIR: /home/ubuntu/ui-archive
                UI_TEMP_DIR: ${UI_ARCHIVE_DIR}/temp-extract
              tasks:
                - script: |
                    #!/bin/bash
                    set -e

                    mkdir -p "${UI_ARCHIVE_DIR}"
                    mkdir -p "${UI_TEMP_DIR}"
                    mkdir -p "${UI_TARGET_DIR}"

                    UI_FILE=$(ls -t "${BUILD_DIR}"/*.ui.*.tar.gz 2>/dev/null | head -n 1)

                    if [ -z "$UI_FILE" ]; then
                      echo "No UI build file found in ${BUILD_DIR}"
                      exit 1
                    fi

                    tar -xzf "$UI_FILE" -C "${UI_TEMP_DIR}"

                    rsync -a --delete "${UI_TEMP_DIR}/" "${UI_TARGET_DIR}/"

                    chmod -R 755 "${UI_TARGET_DIR}"

                    echo "Frontend deployed successfully to ${UI_TARGET_DIR}"
             
environments:
  Frontandbackend:
    pipelines:
      - frontend-deployment