format_version: 10
pipelines:
  GOCD-pipeline-as-code:
    group: default
    environment_variables:
      ENVIRONMENT_NAME: deployandtest
    materials:
      - git:
          url: https://github.com/suryaveerubhotla/simple-ui.git
          branch: main
    stages:
      - name: DeployAndTest
        jobs:
          - name: DeployJar
            environment_variables:
              TARGET_DIR: /home/ubuntu/GOCDpipelineascode
              WORKSPACE: /var/lib/go-agent/pipelines/JarDeploymentPipeline
            tasks:
              - exec:
                  command: mkdir
                  arguments:
                    - -p
                    - /home/ubuntu/GOCDpipelineascode
              - exec:
                  command: cp
                  arguments:
                    - /var/lib/go-agent/pipelines/JarDeploymentPipeline/HelloWorld.jar
                    - /home/ubuntu/GOCDpipelineascode/
              - exec:
                  command: chmod
                  arguments:
                    - "755"
                    - /home/ubuntu/GOCDpipelineascode/HelloWorld.jar
              - exec:
                  command: echo
                  arguments:
                    - JAR file has been successfully deployed to /home/ubuntu/GOCDpipelineascode
