format_version: 10
pipelines:
  GOCD-pipeline-as-code:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    environment_variables:
      ENVIRONMENT_NAME: deployandtest
      TARGET_DIR: /home/ubuntu/GOCDpipelineascode
      WORKSPACE: /var/lib/go-agent/pipelines/JarDeploymentPipeline
    materials:
      git-c05074b:
        git: https://github.com/suryaveerubhotla/simple-ui.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - DeployAndTest:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: success
          jobs:
            run-commands:
              timeout: 0
              resources:
                - ubuntu
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - |
                        mkdir -p "${TARGET_DIR}" && \
                        echo "Created directory: ${TARGET_DIR}" && \
                        if [ -f "${WORKSPACE}/HelloWorld.jar" ]; then
                          cp "${WORKSPACE}/HelloWorld.jar" "${TARGET_DIR}/" && \
                          chmod 755 "${TARGET_DIR}/HelloWorld.jar" && \
                          echo "JAR file has been successfully deployed to ${TARGET_DIR}";
                        else
                          echo "ERROR: HelloWorld.jar not found in ${WORKSPACE}"; exit 1;
                        fi
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - |
                        if [ -f "/home/ubuntu/CIS-CAT Lite Assessor v4.43.0.zip" ]; then
                          cp "/home/ubuntu/CIS-CAT Lite Assessor v4.43.0.zip" "${TARGET_DIR}/" && \
                          echo "Copied CIS-CAT Lite Assessor v4.43.0.zip to ${TARGET_DIR}" && \
                          unzip -o "${TARGET_DIR}/CIS-CAT Lite Assessor v4.43.0.zip" -d "${TARGET_DIR}" && \
                          echo "Unzipped CIS-CAT Lite Assessor v4.43.0.zip in ${TARGET_DIR}";
                        else
                          echo "ERROR: CIS-CAT Lite Assessor v4.43.0.zip not found in /home/ubuntu"; exit 1;
                        fi

environments:
  deployandtest:
    pipelines:
      - GOCD-pipeline-as-code
