format_version: 10
pipelines:
  GOCD-pipeline-as-code:
    group: default
    environment_variables:
      ENVIRONMENT_NAME: deployandtest
    materials:
      git:
        url: https://github.com/suryaveerubhotla/simple-ui.git
        branch: main
    stages:
      - name: Deploy-and-test
        jobs:
          - name: DeployJar
            environment_variables:
              TARGET_DIR: /home/ubuntu/GOCDpipelineascode
              WORKSPACE: /var/lib/go-agent/pipelines/JarDeploymentPipeline
            tasks:
              - exec:
                  command: mkdir
                  arguments:
                    - -p
                    - "{{TARGET_DIR}}"
              - exec:
                  command: cp
                  arguments:
                    - "{{WORKSPACE}}/HelloWorld.jar"
                    - "{{TARGET_DIR}}/"
              - exec:
                  command: chmod
                  arguments:
                    - "755"
                    - "{{TARGET_DIR}}/HelloWorld.jar"
              - exec:
                  command: echo
                  arguments:
                    - JAR file has been successfully deployed to {{TARGET_DIR}}
