---
format_version: 10
pipelines:
  GOCD-pipeline-as-code:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-c05074b:
        git: https://github.com/suryaveerubhotla/simple-ui.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - Deploy-and-test:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
            allow_only_on_success: false
          jobs:
            run-commands:
              timeout: 0
              variables:
                BUILD_DIR: /home/ubuntu/builds
                TARGET_DIR: /home/ubuntu/pprime-ssquare
                ARCHIVE_DIR: /home/ubuntu/archive
                SERVICE: PrimeSquare.service
                TEMP_DIR: ${ARCHIVE_DIR}/temp-extract
              tasks:
                - exec:
                    command: sudo
                    arguments:
                      - systemctl
                      - stop
                      - PrimeSquare.service
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - |
                        echo "Processing build..."
                        echo "BUILD_DIR=${BUILD_DIR}"
                        echo "TARGET_DIR=${TARGET_DIR}"
                        echo "ARCHIVE_DIR=${ARCHIVE_DIR}"
                        echo "TEMP_DIR=${TEMP_DIR}"

                        if [ ! -d "${BUILD_DIR}" ]; then
                          echo "Build directory ${BUILD_DIR} does not exist!"
                          exit 1
                        fi

                        LATEST_BUILD=$(ls -t ${BUILD_DIR}/*.zip 2>/dev/null | head -n 1)

                        if [ -z "${LATEST_BUILD}" ]; then
                          echo "No builds found in ${BUILD_DIR}!"
                          exit 1
                        fi

                        echo "Found latest build: ${LATEST_BUILD}"

                        if [ ! -d "${TARGET_DIR}" ]; then
                          echo "Target directory ${TARGET_DIR} does not exist. Creating..."
                          mkdir -p "${TARGET_DIR}" || { echo "Failed to create ${TARGET_DIR}"; exit 1; }
                        fi

                        echo "Preparing extraction..."
                        mkdir -p "${TEMP_DIR}" "${ARCHIVE_DIR}" || { echo "Failed to create directories"; exit 1; }

                        echo "Extracting build to temporary directory: ${TEMP_DIR}..."
                        unzip -o "${LATEST_BUILD}" -d "${TEMP_DIR}" || { echo "Failed to unzip build"; exit 1; }

                        echo "Copying core-*.jar to ${TARGET_DIR}..."
                        JAR_FILE=$(find "${TEMP_DIR}" -type f -name "core-*.jar" | head -n 1)

                        if [ -z "${JAR_FILE}" ]; then
                          echo "No core-*.jar file found in the extracted build!"
                          exit 1
                        fi

                        cp "${JAR_FILE}" "${TARGET_DIR}" || { echo "Failed to copy JAR file"; exit 1; }
                        echo "Cleaning up temporary directory..."
                        rm -rf "${TEMP_DIR}" || { echo "Failed to clean up"; exit 1; }

                        echo "Build processing complete."
                - exec:
                    command: sudo
                    arguments:
                      - systemctl
                      - restart
                      - PrimeSquare.service
              run_if: passed
environments:
  deployandtest:
    pipelines:
      - GOCD-pipeline-as-code
