pipelines:
  test-pipeline:
    group: test-group
    label_template: "${COUNT}"
    materials:
      git:
        url: https://github.com/suryaveerubhotla/simple-ui.git
        branch: main
    stages:
      - test-stage:
          jobs:
            - test-job:
                tasks:
                  - exec:
                      command: echo
                      arguments:
                        - "Hello, GoCD Pipeline!"
