format_version: 10
pipelines:
    group: deployment-group
    label_template: ${COUNT}
    lock_behavior: none
    display_order: 1
    materials:
      git-backend:
        git: https://github.com/suryaveerubhotla/simple-ui.git
        shallow_clone: false
        auto_update: true
        branch: main
    parameters:
      DROP_DB: Yes/No
    stages:
      - Deploy:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
          jobs:
            run-commands:
              timeout: 0
              variables:
                BUILD_DIR: /home/ubuntu/builds
                BE_TARGET_DIR: /home/ubuntu/prime-square
                SERVICE: PrimeSquare.service
                DB_SCRIPTS_DIR: /home/ubuntu/prime-square/database-scripts
                DB_USER: psdbadmin
                DB_PASS: 6%EOm@Te1sb19Th6
                SFTP_HOST: 172.16.7.116
                SFTP_USER: surya
                SFTP_UPLOADS_DIR: uploads
                DROP_DB: YES 
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - |
                        export BUILD_DIR=/home/ubuntu/builds
                        export BE_TARGET_DIR=/home/ubuntu/prime-square
                        export BE_ARCHIVE_DIR=/home/ubuntu/archive
                        export SERVICE=PrimeSquare.service
                        export DB_SCRIPTS_DIR=/home/ubuntu/prime-square/database-scripts
                        export DB_USER=psdbadmin
                        export DB_PASS=6%EOm@Te1sb19Th6
                        export SFTP_HOST=172.16.7.116
                        export SFTP_USER=surya
                        export SFTP_KEY=/var/go/.ssh/id_rsa
                        export SFTP_UPLOADS_DIR=uploads
                        export DROP_DB=${DROP_DB}

                        echo "Checking if service ${SERVICE} exists..."
                        if [ -f /etc/systemd/system/${SERVICE} ]; then
                          echo "${SERVICE} exists. Checking service status..."
                          sudo systemctl status ${SERVICE} > /dev/null 2>&1
                          if [ $? -eq 0 ]; then
                            echo "${SERVICE} is running. Stopping the service..."
                            sudo systemctl stop ${SERVICE} || { echo "Failed to stop ${SERVICE}"; exit 1; }
                          else
                            echo "${SERVICE} is not running."
                          fi
                        else
                          echo "${SERVICE} does not exist. Proceeding..."
                        fi

                        echo "Checking and creating BUILD_DIR if needed..."
                        if [ ! -d "${BUILD_DIR}" ]; then
                          echo "BUILD_DIR does not exist. Creating ${BUILD_DIR}..."
                          mkdir -p "${BUILD_DIR}" || { echo "Failed to create ${BUILD_DIR}"; exit 1; }
                        else
                          echo "BUILD_DIR exists. Using existing ${BUILD_DIR}..."
                        fi

                        echo "Checking for existing ps_be_*.zip files in BUILD_DIR..."
                        if ls "${BUILD_DIR}/ps_be_*.zip" > /dev/null 2>&1; then
                          echo "Found existing ps_be_*.zip files. Removing them..."
                          sudo rm -f "${BUILD_DIR}/ps_be_*.zip" || { echo "Failed to remove existing zip files"; exit 1; }
                        else
                          echo "No existing ps_be_*.zip files found. Proceeding..."
                        fi

                        echo "Accessing SFTP machine to fetch the backend zip file..."
                        sftp -o StrictHostKeyChecking=no -i /var/go/.ssh/id_rsa ${SFTP_USER}@${SFTP_HOST} <<EOF
                        cd ${SFTP_UPLOADS_DIR}
                        get ps_be_*.zip ${BUILD_DIR}/backend.zip
                        bye
                        EOF
                        if [ $? -ne 0 ]; then
                          echo "Failed to fetch backend.zip from SFTP."
                          exit 1
                        fi

                        echo "Checking and creating BE_TARGET_DIR if needed..."
                        if [ ! -d "${BE_TARGET_DIR}" ]; then
                          echo "BE_TARGET_DIR does not exist. Creating ${BE_TARGET_DIR}..."
                          mkdir -p "${BE_TARGET_DIR}" || { echo "Failed to create ${BE_TARGET_DIR}"; exit 1; }
                        else
                          echo "BE_TARGET_DIR exists. Using existing ${BE_TARGET_DIR}..."
                        fi

                        echo "Changing permissions of BE_TARGET_DIR to ubuntu:ubuntu..."
                        sudo chown -R ubuntu:ubuntu "${BE_TARGET_DIR}" || { echo "Failed to change permissions of BE_TARGET_DIR"; exit 1; }

                        echo "Copying and unzipping the backend artifacts to BE_TARGET_DIR..."
                        sudo cp "${BUILD_DIR}/backend.zip" "${BE_TARGET_DIR}/" || { echo "Failed to copy zip file"; exit 1; }
                        sudo unzip -o "${BE_TARGET_DIR}/backend.zip" -d "${BE_TARGET_DIR}" || { echo "Failed to unzip backend.zip"; exit 1; }

                        echo "Removing the zip file from BE_TARGET_DIR..."
                        sudo rm -f "${BE_TARGET_DIR}/backend.zip"

                        echo "Listing extracted files in BE_TARGET_DIR..."
                        ls -l "${BE_TARGET_DIR}"

                        echo "Changing permissions of BE_TARGET_DIR and BUILD_DIR to ubuntu:ubuntu..."
                        sudo chown -R ubuntu:ubuntu "${BE_TARGET_DIR}" || { echo "Failed to change permissions of BE_TARGET_DIR"; exit 1; }
                        sudo chown -R ubuntu:ubuntu "${BUILD_DIR}" || { echo "Failed to change permissions of BUILD_DIR"; exit 1; }

                        echo "Checking and copying service file if needed..."
                        if [ ! -f /etc/systemd/system/${SERVICE} ]; then
                          sudo cp "${BE_TARGET_DIR}/service/${SERVICE}" /etc/systemd/system/ || { echo "Failed to copy service file"; exit 1; }

                          echo "Enabling the service..."
                          sudo systemctl enable ${SERVICE} || { echo "Failed to enable ${SERVICE}"; exit 1; }
                        else
                          echo "Service file already exists. Skipping copy."
                        fi

                        echo "Making wrapper.sh executable..."
                        sudo chmod +x "${BE_TARGET_DIR}/wrapper.sh" || { echo "Failed to make wrapper.sh executable"; exit 1; }

                        echo "Reloading systemd daemon..."
                        sudo systemctl daemon-reload || { echo "Failed to reload systemd daemon"; exit 1; }

                        if [ "${DROP_DB}" == "YES" ]; then
                          echo "Executing database scripts as DROP_DB is set to YES..."
                          sudo chmod -R +x "${DB_SCRIPTS_DIR}" || { echo "Failed to give execute permissions to database scripts"; exit 1; }

                          mysql < "${DB_SCRIPTS_DIR}/ddl_drop_schema_script.sql" -u ${DB_USER} -p${DB_PASS} || { echo "Failed to execute ddl_drop_schema_script.sql"; exit 1; }
                          mysql < "${DB_SCRIPTS_DIR}/idfc_primesquare_workflow_ddl_dml.sql" -u ${DB_USER} -p${DB_PASS} || { echo "Failed to execute primesquare_workflow_ddl_dml.sql"; exit 1; }
                          mysql < "${DB_SCRIPTS_DIR}/ddl_create_scripts.sql" -u ${DB_USER} -p${DB_PASS} || { echo "Failed to execute ddl_create_scripts.sql"; exit 1; }
                          mysql < "${DB_SCRIPTS_DIR}/dml_insert_scripts.sql" -u ${DB_USER} -p${DB_PASS} || { echo "Failed to execute dml_insert_scripts.sql"; exit 1; }
                          mysql < "${DB_SCRIPTS_DIR}/ps_index_create.sql" -u ${DB_USER} -p${DB_PASS} || { echo "Failed to execute ps_index_create.sql"; exit 1; }
                        else
                          echo "Skipping database scripts execution as DROP_DB is set to NO."
                        fi

                        echo "Starting service..."
                        sudo systemctl start ${SERVICE} || { echo "Failed to start ${SERVICE}"; exit 1; }
                        sudo systemctl status ${SERVICE}

                        echo "Deployment complete."
              resources:
                - ubuntu
              environment_variables:
                GOCD_ENVIRONMENT: Frontandbackend

environments:
  Frontandbackend:
    pipelines:
      - parameters
