format_version: 10
pipelines:
  replacing-jar:
    group: deployment-group
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-c05074b:
        git: https://github.com/suryaveerubhotla/simple-ui.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - Deploy-and-test:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
            allow_only_on_success: false
          jobs:
            run-commands:
              timeout: 0
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - |
                        echo "Exporting environment variables..."
                        export BUILD_DIR=/home/ubuntu/builds
                        export BE_TARGET_DIR=/home/ubuntu/prime-square
                        export BE_ARCHIVE_DIR=/home/ubuntu/archive/
                        export Backup=/home/ubuntu/Backup
                        export SERVICE=PrimeSquare.service
                        export SFTP_HOST=172.16.7.116
                        export SFTP_USER=surya
                        export SFTP_KEY=/var/go/.ssh/id_rsa
                        export SFTP_UPLOADS_DIR=uploads
                        
                        echo "creating BUILD_DIR if needed..."
                        mkdir -p "${BUILD_DIR}"
                        echo "Checking for existing backend files in BUILD_DIR..."
                        sudo rm -f "${BUILD_DIR}/ps_be_*.zip"
                        echo "Accessing SFTP machine to fetch the backend zip file..."
                        sftp -o StrictHostKeyChecking=no -i "${SFTP_KEY}" "${SFTP_USER}@${SFTP_HOST}" <<EOF
                        cd ${SFTP_UPLOADS_DIR}
                        get ps_be_*.zip ${BUILD_DIR}
                        bye
                        EOF

                        if [ $? -ne 0 ]; then
                          echo "Failed to fetch backend zip file from SFTP."
                          exit 1
                        fi

                        if systemctl is-active --quiet ${SERVICE}; then
                          sudo systemctl stop ${SERVICE}
                        fi

                        echo "Creating BE_ARCHIVE_DIR and Backup"
                        mkdir -p "${BE_ARCHIVE_DIR}"
                        mkdir -p "${Backup}"

                        echo "Checking for backend (ps_be)..."
                        BE_ZIP=$(ls ${BUILD_DIR}/ps_be*.zip 2>/dev/null | head -n 1)
                        if [ -z "${BE_ZIP}" ]; then
                          echo "No ps_be zip file found in ${BUILD_DIR}!"
                          exit 1
                        fi

                        echo "Unzip BE_ZIP to BE_ARCHIVE_DIR..."
                        unzip -o "${BE_ZIP}" -d "${BE_ARCHIVE_DIR}"

                        echo "Checking for JAR file..."
                        JAR_FILE=$(find "${BE_ARCHIVE_DIR}" -type f -name "core-*.jar" | head -n 1)
                        if [ -z "${JAR_FILE}" ]; then
                          echo "No core-*.jar file found in the archive!"
                          exit 1
                        fi

                        echo "Archiving existing JAR file(s)..."
                        if ls "${BE_TARGET_DIR}/core-*.jar" > /dev/null 2>&1; then
                          sudo mv "${BE_TARGET_DIR}/core-*.jar" "${Backup}/core-$(date +%F-%T).jar"
                          echo "Listing files in Backup..."
                          ls -l "${Backup}"
                        fi

                        echo "Copying new JAR file to BE_TARGET_DIR..."
                        sudo cp "${JAR_FILE}" "${BE_TARGET_DIR}"

                        echo "Cleaning up BE_ARCHIVE_DIR..."
                        rm -rf "${BE_ARCHIVE_DIR}/*"

                        echo "listing files in BE_ARCHIVE_DIR"
                        ls -l "${BE_ARCHIVE_DIR}"

                        echo "Listing files in BE_TARGET_DIR..."
                        ls -l "${BE_TARGET_DIR}"

                        echo "Enabling the service..."
                          sudo systemctl enable ${SERVICE}

                        echo "Jar replaced successfully . Starting the service..."
                        sudo systemctl daemon-reload
                        sudo systemctl start ${SERVICE}
                        sudo systemctl status ${SERVICE}

environments:
  Frontandbackend:
    pipelines:
      - replacing-jar
