---
format_version: 10
pipelines:
  sample:
    group: deployment-group
    label_template: ${COUNT}
    lock_behavior: none
    display_order: 2
    materials:
      git-frontend:
        git: https://github.com/suryaveerubhotla/simple-ui.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - Deploy:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
          jobs:
            run-commands:
              timeout: 0
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - >
                        echo "Exporting environment variables..."

                        export UI_ARCHIVE_DIR=/home/ubuntu/ui-archive

                        export TARGET_DIR=/var/www/html/prime-square

                        export SFTP_HOST=172.16.7.116

                        export SFTP_USER=surya

                        export SFTP_KEY=/var/go/.ssh/id_rsa

                        export SFTP_UPLOADS_DIR=uploads

                        export TARGET_HOST=172.16.7.112


                        echo "Creating UI_ARCHIVE_DIR if not exists..."

                        mkdir -p "${UI_ARCHIVE_DIR}" || echo "Directory ${UI_ARCHIVE_DIR} already exists."


                        echo "Setting permissions for UI_ARCHIVE_DIR..."

                        sudo chmod -R 775 "${UI_ARCHIVE_DIR}" || { echo "Failed to set permissions for UI_ARCHIVE_DIR"; exit 1; }

                        sudo chown -R ubuntu:ubuntu "${UI_ARCHIVE_DIR}" || { echo "Failed to change ownership of UI_ARCHIVE_DIR"; exit 1; }


                        echo "Fetching the latest UI build from SFTP server..."

                        latest_ui_file=$(ssh -o StrictHostKeyChecking=no -i "${SFTP_KEY}" "${SFTP_USER}@${SFTP_HOST}" "cd ${SFTP_UPLOADS_DIR} && ls -t ui_*.zip 2>/dev/null | head -n 1")


                        if [ -z "$latest_ui_file" ]; then
                          echo "No UI build found on SFTP server. Exiting."
                          exit 1
                        fi


                        echo "Latest UI file found: $latest_ui_file"

                        sftp -o StrictHostKeyChecking=no -i "${SFTP_KEY}" "${SFTP_USER}@${SFTP_HOST}" <<EOF

                        cd ${SFTP_UPLOADS_DIR}

                        get "$latest_ui_file" ${UI_ARCHIVE_DIR}

                        bye

                        EOF


                        echo "Listing files in UI_ARCHIVE_DIR..."

                        ls -l "${UI_ARCHIVE_DIR}"


                        echo "Stopping Apache2 service..."

                        sudo systemctl stop apache2 || { echo "Failed to stop Apache2"; exit 1; }


                        echo "Removing existing UI files in ${TARGET_DIR}..."

                        sudo rm -rf "${TARGET_DIR}" || { echo "Failed to remove existing files in ${TARGET_DIR}"; exit 1; }


                        echo "Unzipping UI build to ${TARGET_DIR}..."

                        sudo unzip -o "${UI_ARCHIVE_DIR}/$latest_ui_file" -d "${TARGET_DIR}" || { echo "Failed to unzip UI build"; exit 1; }


                        echo "Replacing target host in the UI files..."

                        sudo sed -i "s#https://ps-targethost:3804/prime-square#http://${TARGET_HOST}/prime-square#g" "${TARGET_DIR}/main.e1f206db06620922.js"

                        sudo sed -i "s#https://ps-targethost:3804/prime-square#http://${TARGET_HOST}/prime-square#g" "${TARGET_DIR}/assets/environment/environment.json"


                        echo "Starting Apache2 service..."

                        sudo systemctl start apache2 || { echo "Failed to start Apache2"; exit 1; }


                        echo "Frontend deployment completed successfully."
              resources:
                - ubuntu
              environment_variables:
                GOCD_ENVIRONMENT: Frontandbackend
environments:
  Frontandbackend:
    pipelines:
      - sample
